### ISSUE TITLE
Recuperer les infos de plusieurs thermostats ?

### ISSUE THREAD

**Issue by aldoushx** [KiboOst/php-simpleQivivoAPI#1]
Bonjour,
Merci pour ton travail sur cette API.
Je suis équipé de 2 thermostats associés au même compte, est-il possible de récupérer les infos du 2eme thermostat ?
Car la requete ne remonte que les infos du 1er thermostat associé au compte, et pas celles d'un thermostat d'une autre residence.
Je vois par exemple dans l'API officielle que la fonction GET https://data.qivivo.com/api/v2/devices/thermostats/:thermostat_uuid/info appelle l'uuid du thermostat concerné, donc on doit bien pouvoir récupérer les info d'autres thermostats, mais je ne vois pas comment récupérer l'uuid du 2eme et obtenir les mêmes infos que pour le 1er (temperature, ordre...)

**Comment by KiboOst** [comment]
Bonjour,
En effet je ne le gère pas actuellement. Je dois refaire beaucoup de chose suite à la migration des interfaces Comap, je regarderai après.

**Comment by KiboOst** [comment]
Bonjour,

L'API officielle actuelle est deprecated, elle ne dialogue plus avec les modules.
J'ai refait une API complète, basée sur la nouvelle API Qivivo utilisée par leur site et apps, mais pas encore documentée: https://github.com/KiboOst/php-qivivoAPI

Pour gérer plusieurs thermostat, essaye mais pas sur que çà fonctionne en l'état. Il me faudrait une config pour tester, n'ayant qu'un seul thermostat.
